# 钉钉 rss 推送机器人
name: DingDingRssBot

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 9 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check the current timezone database
      run: |
        ls /usr/share/zoneinfo
        echo "---"
        date
        echo "---"
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up Python Version
      uses: actions/setup-python@master
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd robot
        pip install -r requirements.txt
    - name: send rss
      env:
        DD_WEBHOOK: ${{ secrets.webhook }}
        DD_SECRET: ${{ secrets.secret }}
      run: |
        cd robot
        python rss.py
    - name: Github commit and push
      uses: Smart-Transportation/push@master
      with:
        branch: main
        github_token: ${{ secrets.TOKEN }}

