# 钉钉 rss 推送机器人
name: DingDingRssBot

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 9 * * *'

env:
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
    - name: Set up Python Version
      uses: actions/setup-python@master
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        cd robot
        pip install -r requirements.txt
    - name: send rss
      env:
        DD_WEBHOOK: ${{ secrets.webhook }}
        DD_SECRET: ${{ secrets.secret }}
      run: |
        cd robot
        python rss.py
    - name: Commit
      run: |
        git config --global user.email hjjixx@hotmail.com
        git config --global user.name mumumi
        git add .
        git commit -m "update" -a
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: main
        github_token: ${{ secrets.TOKEN }}

